site_name: Mkdocs overview
nav:
  - Home: 'index.md' # <- Uses this name in TOC instead of top level heading
  - Junk Pages: # <- Blank TOC category heading
    - 'page1.md'
    - 'page2.md'
  - User Guide: 
    - 'extension examples.md'
    - 'markdown examples.md'
  - 'my autodoc attempt.md'
theme: readthedocs #mkdocs
markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.progressbar # Doesnt work in readthedocs theme
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.magiclink

plugins:
  - search
  - hello-dolly
  - dodoc
